// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectApi.DataContext;

namespace ProjectApi.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20190919154033_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectApi.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(255);

                    b.Property<int>("Age");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<string>("Intrests")
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("User");

                    b.HasData(
                        new { ID = 1, Address = "Address", Age = 30, FirstName = "John", Intrests = "Singing", LastName = "Robert" },
                        new { ID = 2, Address = "Address", Age = 40, FirstName = "Richard", Intrests = "Browsing", LastName = "Dennis" },
                        new { ID = 3, Address = "Address", Age = 44, FirstName = "Richard", Intrests = "Rafting", LastName = "Joe" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
